export const typeBackgrounds = {
  bug: 'bg-gradient-to-br from-bug to-bug-600',
  dragon: 'bg-gradient-to-br from-dragon to-dragon-600',
  electric: 'bg-gradient-to-br from-electric to-electric-600',
  fairy: 'bg-gradient-to-br from-fairy to-fairy-600',
  fighting: 'bg-gradient-to-br from-fighting to-fighting-600',
  fire: 'bg-gradient-to-br from-fire to-fire-600',
  flying: 'bg-gradient-to-br from-flying to-flying-600',
  ghost: 'bg-gradient-to-br from-ghost to-ghost-600',
  grass: 'bg-gradient-to-br from-grass to-grass-600',
  ground: 'bg-gradient-to-br from-ground to-ground-600',
  ice: 'bg-gradient-to-br from-ice to-ice-600',
  normal: 'bg-gradient-to-br from-normal to-normal-600',
  poison: 'bg-gradient-to-br from-poison to-poison-600',
  psychic: 'bg-gradient-to-br from-psychic to-psychic-600',
  rock: 'bg-gradient-to-br from-rock to-rock-600',
  steel: 'bg-gradient-to-br from-steel to-steel-600',
  water: 'bg-gradient-to-br from-water to-water-600',
};